### ISSUE TITLE
Reference secrets in CR according to naming schemes of Kubernetes

### ISSUE THREAD

**Issue by Knappek** [Knappek/mongodbatlas-operator#1]
Reference secrets in CR according to the naming scheme by using 

```yaml
- name: SECRET_USERNAME
  valueFrom:
    secretKeyRef:
      name: backend-user
      key: backend-username
``` 

Similar to: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#define-container-environment-variables-using-secret-data
