### ISSUE TITLE
Implement creating a Backup before deleting a cluster

### ISSUE THREAD

**Issue by Knappek** [Knappek/mongodbatlas-operator#6]
Before deleting a cluster, it would be nice to create a snapshot. The snapshot can either be stored as a PV or on an external storage such as Amazon S3, GCS or Azure storage account.
This feature should be optional and it can be implemented as an additional block in the `spec`of `MongoDBAtlasCluster`. For example

```yaml
apiVersion: knappek.com/v1alpha1
kind: MongoDBAtlasCluster
metadata:
  name: example-mongodbatlascluster
spec:
  ...
  createSnapshotBeforeDeletion:
    name: my-safety-snapshot
    provider: pv
  ...
```
